export const ADDNEW_TASK = 'ADDNEW_TASK';
export const GETALL_TASK = 'GETALL_TASK';
export const UPDATESTATUS_TASK = 'UPDATESTATUS_TASK';
export const UPDATEALL_TASK = 'UPDATEALL_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETEALL_TASKS = 'DELETEALL_TASKS';
export const UPDATESELECTED_STATUS = 'UPDATESELECTED_STATUS';